version: 2.1
jobs:
  build:
    docker:
      - image: python:3.7-slim-buster
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
            python -v
      - run:
          name: CodCov
          command: |
            export CODECOV_TOKEN=`42dc6b18-1582-4f40-b780-644325f9b874`
            bash <(curl -s https://codecov.io/bash)

