version: 2.1
jobs:
  build:
    docker:
      - image: python:3.7-slim-buster
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Env preparation
          command: |
            pip install poetry
            poetry install
      - run:
          name: Test
          command: |
            poetry shell
            pytest --cov=./
      - run:
          name: CodCov
          command: |
            apt-get update
            apt-get -y install curl
            export CODECOV_TOKEN=`42dc6b18-1582-4f40-b780-644325f9b874`
            bash <(curl -s https://codecov.io/bash)

